import { Inter } from "next/font/google";

export const metadata = {
  title:  {
    default: 'Next Tutorial',
    template: '%s | Teste'
  },
  description: 'Generated by Next.js',
}

const inter = Inter({subsets: ["latin"]});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{backgroundColor: "green"}}>
          Cabeçalho da aplicação
        </header>
        {children}
        <footer style={{backgroundColor: "green"}}>
          Rodapé da aplicação
        </footer>
      </body>
    </html>
  )
}
